apiVersion: v1
kind: Service
metadata:
  name: i15j-rcs
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: i15j-rcs
  type: LoadBalancer
  loadBalancerIP: 172.23.169.93 #optional field for a specific IP. You can omit this
  externalTrafficPolicy: Cluster

